### PR TITLE
Add vector logos

### PR DESCRIPTION
**Pull request by Kubuxu**
EDIT:
Even more updated :smile: :  https://ipfs.io/ipfs/QmTgtbb4LckHaXh1YhpNcBu48cFY8zgT1Lh49q7q7ksf3M/

It was first draw in CAD so it is mathematically correct. If you want I can also publish files from Fusion360

### CODE REVIEW

**Comment by jbenet** [comment]
> They look a bit different than original but raster versions have this stripe also just it is hardly visible.
> IMHO it adds a lot to the logo itself. I can reduce size of the stripe if you want.
> (They also might be just a mistake in original raster but I liked them)

yeah they were a mistake. we should rm the stripes, sory

i'd like to make the logo look more 3D. not sure what to do there. we could get a proper logo designer involved. (stripes not quite what i mean)

**Comment by Kubuxu** [comment]
It is easy to fix. Looking into some sort of shading but I am not an artist (also I got it upside down :smile: )

**Comment by Kubuxu** [comment]
zrzut ekranu 2016-02-01 16 31 06

How is that, I will also try to add some highlights.

**Comment by Kubuxu** [comment]
I can make it look like that: https://ipfs.io/ipfs/QmTSGEspEnA1t7vZNPZ3297o4DU5unB8fd13AWT2LrzTPW

**Comment by Kubuxu** [comment]
@jbenet It currently looks like that:
https://ipfs.io/ipfs/QmUgrh4j3Hxf6Su3hS3A5mdBYi6epmWnAeXEg1yR1Rc5sh/#vector

Exacely as the orginal. If you like I can reraster current bitmaps in separate PR so they are symmetric (they are really crooked).

And we can talk about possible redesign/shading in other issue.

**Comment by jbenet** [comment]
@Kubuxu i like https://ipfs.io/ipfs/QmTSGEspEnA1t7vZNPZ3297o4DU5unB8fd13AWT2LrzTPW very much! :+1:

**Comment by jbenet** [comment]
Let's go with the 3D version for now. eventually we may redesign more, but this is a good step fwd.

**Comment by jbenet** [comment]
@Kubuxu could you license it CC-BY and reassign copyright to Protocol Labs? For official logos, we have to trademark whatever we use so that it is not used to endorse products without permission, etc. (we're following what Linux Foundation did with Tux. -- though if you know a better way i'm all ears). It will then be transferred to "The Interplanetary Foundation" once it exists (on my TODOs later this year.

**Comment by Kubuxu** [comment]
No problem, if you have some copy-pasta ready it would be even better.

(Maybe you want already to place a ™ there, you don't have to do anything to claim it as your trademark).

Working to make them all shaded. White versions will looks a bit worst on white background but this is not an issue (you probably don't want to use white version on white background either way).

This is how they look now: https://ipfs.io/ipfs/QmZegfkyqZXJGxJynvLcDN64UuKoQ85CUDhPHtJRF5CCoc/#vector

It would be also great to know what font have you used for original text.

Note to self: it is Oxygen Bold, 160px, -3px letter spacing

**Comment by jbenet** [comment]
- Font: I used Oxygen in all caps.
- Re copyright, i'll look at how to do it. there's probably just some statement you sign. (legal world tooling sucks)

**Comment by Kubuxu** [comment]
I decided to split the text from the logo (in case the text is next to the logo). Including them separately in HTML very simple and it allows for changes much easier and simpler.

I can still raster those images joined and also I will work on raster script.
https://ipfs.io/ipfs/QmQ11xxMhorF5yFm7sSSc61E8MCpXWSwk6VQ52bmwF5yHY/

**Comment by Kubuxu** [comment]
I've written a rasterisation script, regenerated all rasters.
I've reorganised them as some of them are being generated and some are not so I've put those being generated inside separate directory. 

Everything looks like that: http://ipfs.io/ipfs/QmTgtbb4LckHaXh1YhpNcBu48cFY8zgT1Lh49q7q7ksf3M

**Comment by lidel** [comment]
@jbenet  any chance to give this PR a bump? 
I can't wait to use them in [ipfs-firefox-addon](https://github.com/lidel/ipfs-firefox-addon)  :sparkles:

**Comment by Kubuxu** [comment]
I think it would be awesome to release refreashed logo with 0.4.0.

**Comment by RichardLitt** [comment]
@Kubuxu does this match the spec at http://hexb.in/sticker.html?

**Comment by RichardLitt** [comment]
@Kubuxu Can you throw me a version of these that looks like [this](https://www.stickermule.com/marketplace/4930-ipfs) in .ai or .psd format, so that I can upload the new sticker to stickermule?

**Comment by Kubuxu** [comment]
If you scale it, it should. I don't remember spatial dimensions (they are 512 pixels) I've set but it is easy rescale to change.

I don't own any Adobe software so I won't be able to provide you with .ai or .psd.

**Comment by RichardLitt** [comment]
Cool. Thanks. Working on it.

**Comment by jbenet** [comment]
we didnt ship the refreshed logo with 0.4.0 -- we should soon :)

**Comment by jbenet** [comment]
Im just going to merge this.

**Pull request merged**
